using AssignmentModule6Svr;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace AssignmentModule6Svr.Classes
{
    /// <summary>
    /// Represents a customer with associated invoices and phone numbers.
    /// IDs are auto-generated by the system and should not be manually set.
    /// </summary>
    public class Customer
    {
        /// <summary>
        /// Unique identifier for the customer. Auto-generated by the system.
        /// </summary>
        [Range(0, long.MaxValue, ErrorMessage = "Id must be greater than or equal zero.")]
        public long Id { get; set; }
        
        /// <summary>
        /// Customer's name (typically a company name).
        /// </summary>
        public string? Name { get; set; }
        
        /// <summary>
        /// Customer's email address.
        /// </summary>
        public string? Email { get; set; }
        
        /// <summary>
        /// Collection of invoices associated with this customer.
        /// </summary>
        public List<Invoice>? Invoices { get; set; } = new List<Invoice>();
        
        /// <summary>
        /// Calculated property that returns the sum of all invoice amounts for this customer.
        /// Returns 0 if there are no invoices.
        /// </summary>
        public decimal Balance => Invoices?.Sum(i => i.Amount) ?? 0;
        
        /// <summary>
        /// Collection of phone numbers associated with this customer.
        /// </summary>
        public List<PhoneNumber>? PhoneNumbers { get; set; } = new List<PhoneNumber>();
    }
}
