using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace AssignmentModule6Svr.Classes
{
    /// <summary>
    /// Represents an invoice belonging to a customer.
    /// Invoice IDs are auto-generated globally (unique across all customers).
    /// Invoice numbers must be user-provided and start with "INV".
    /// </summary>
    public class Invoice
    {
        /// <summary>
        /// Unique identifier for the invoice. Auto-generated by the system and globally unique.
        /// </summary>
        [Range(0, long.MaxValue, ErrorMessage = "Id must be greater than or equal zero.")]
        public long Id { get; set; }
        
        /// <summary>
        /// User-provided invoice number. Must start with "INV" and be unique across all customers.
        /// Example: "INV-12345678"
        /// </summary>
        [Required(ErrorMessage = "InvoiceNumber is required.")]
        [RegularExpression(@"^INV.*", ErrorMessage = "InvoiceNumber must start with 'INV'.")]
        public string InvoiceNumber { get; set; } = string.Empty;

        /// <summary>
        /// Foreign key reference to the Customer who owns this invoice.
        /// </summary>
        [Range(0, long.MaxValue, ErrorMessage = "CustomerId must be greater than or equal zero.")]
        public long CustomerId { get; set; }

        /// <summary>
        /// The date the invoice was issued.
        /// </summary>
        public DateTime InvoiceDate { get; set; }

        /// <summary>
        /// The monetary amount of the invoice.
        /// </summary>
        // [Range(typeof(decimal), "0.01", "79228162514264337593543950335", ErrorMessage = "Amount must be a positive value.")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Initializes a new instance of the Invoice class.
        /// </summary>
        public Invoice() { }

    }
}
