using System.ComponentModel.DataAnnotations;

namespace AssignmentModule6Svr.Classes
{
    /// <summary>
    /// Represents a phone number belonging to a customer.
    /// Phone number IDs are auto-generated globally (unique across all customers).
    /// </summary>
    public class PhoneNumber
    {
        /// <summary>
        /// Unique identifier for the phone number. Auto-generated by the system and globally unique.
        /// </summary>
        [Range(0, long.MaxValue, ErrorMessage = "Id must be greater than or equal zero.")]
        public long Id { get; set; }
        
        /// <summary>
        /// Foreign key reference to the Customer who owns this phone number.
        /// </summary>
        [Range(0, long.MaxValue, ErrorMessage = "CustomerId must be greater than or equal zero.")]
        public long CustomerId { get; set; }
        
        /// <summary>
        /// The type of phone number. Must be one of: Mobile, Work, or DirectDial.
        /// </summary>
        [RegularExpression("^(Mobile|Work|DirectDial)$", ErrorMessage = "Type must be Mobile, Work, or DirectDial.")]
        public string? Type { get; set; }
        
        /// <summary>
        /// The phone number string in any format.
        /// </summary>
        public string? Number { get; set; }
        
        /// <summary>
        /// Initializes a new instance of the PhoneNumber class.
        /// </summary>
        public PhoneNumber() { }
    }
}
